### PR TITLE
I8/fix argument null exception

### PR DESCRIPTION
**Pull request by Dentsor**
Implementing Data Transfer Objects (DTOs) instead of returning EF Models directly.
Also disabled PUT/POST/PATCH/DELETE in controllers, as working reverse-mappings is not implemented.

### CODE REVIEW

**Comment by Dentsor** [comment]
Waiting #11, as this branch is based on that one

**Comment by Dentsor** [comment]
[ ] Update docs (readme)
[ ] Remove user.requirements

**Comment by LarsSelbekk** [comment]
Do we really need a commit followed by a commit reverting it? 🤪

**Comment by LarsSelbekk** [comment]
Did you purposefully mark User::Requirements virtual, i.e. lazy-loading? Perhaps some comment explaining why would be helpful

**Comment by Dentsor** [comment]
I wanted it available in the log so I could find it again, as it was a lot of work, but it's not *necessary* any more, I suppose...

User::Requirements is meant to be removed again (out of scope for issue). I see I forgot to remove it from the DTO, though.
User::Requirements is virtual because (IIRC) it is required for EF to overwrite/initialize it.

**Comment by Dentsor** [comment]
Removed the commits in question and remove UserDto::Requirements as well

**Comment by LarsSelbekk** [comment]
Fix pls:
* I don't think it's necessary to keep the commented-out code at line 31 in BadgeController, it's in the log if we need it, and it's obsolete anyway.
* I think it'd be better to use block comment when commenting out large sections of code.
* I think there should be some explanation of what RequirementsProfile actually does - I had to look at the base class to get it.
* There's a missing ```set;``` in ```UserDto::UserID```, making all ids ```0```.


Aside:
* The DTOs seem to be convertible to [records](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records), which would significantly reduce the amount of code required, introduce value equality, auto-generate ToString, and a few other things - I don't know how well EF Core works with them, but I think it'd be fine since they're not added to the database. However, it seems inheritance is a little wonky with the shortest syntax, since you have to declare the properties of all base classes as well, so it might
* I don't really get why `Discriminator` is defined explicitly in `Requirement`. If it can have any name, should probably be called `RequirementType` anyway.

Otherwise, this looks good. The automapper stuff is a little abstract, but you can teach us that in person.

**Comment by Dentsor** [comment]
* Removed unncessary, commented code
* Added comment in RequirementProfile
* Added setter for UserDto::UserID
* Rename Requirement::Discriminator to ::RequirementType

* I have chosen not to make them Records, as I haven't read enough about them, and some features seem to expect .NET 6/C#10, while we're still on .NET 5
  * I'm thinking this can easily be made into a new issue instead.
* I believe Discriminator/RequirementType is necessary in order to access the RequirementType of a Requirement, as a Requirement-instance might represent e.g. a Badge aswell. I believe it's possible to let EF handle it, but then it's not accessible to us, which is handy to have.

**Comment by Dentsor** [comment]
Made two new Issues: #15 and #16

**Pull request merged**
